server:
  port: 8080
spring:
  datasource:
    username: test-user
    password: 1234
    url: jdbc:postgresql://localhost:5431/postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

